In [9]:
import pandas as pd

tabela = pd.read_csv("C:/Users/nacli/OneDrive/Área de Trabalho/Faculdade/AEDS3-main/AEDS3-main/anime.csv")

In [10]:
display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

None

In [11]:
display(tabela["Type"].value_counts())

Type
TV         4996
OVA        3894
Movie      3041
Special    2218
ONA        1907
Music      1469
Unknown      37
Name: count, dtype: int64

In [12]:
tabela = tabela.drop(["Japanese name","English name","Premiered","Score-10","Score-9","Score-8","Score-7","Score-6","Score-5","Score-4","Score-3","Score-2","Score-1","Rating",	"Ranked", "Popularity",	"Members", "Favorites", "Watching", "Completed", "On-Hold", "Dropped",	"Plan to Watch", "Producers", "Licensors", "Studios", "Source","Duration"], axis = 1)
display(tabela)

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,"Apr 3, 1998 to Apr 24, 1999"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,"Sep 1, 2001"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,"Apr 1, 1998 to Sep 30, 1998"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,"Jul 2, 2002 to Dec 24, 2002"
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,"Sep 30, 2004 to Sep 29, 2005"
...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",ONA,Unknown,"Apr 4, 2021 to ?"
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",TV,Unknown,2021 to ?
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",TV,Unknown,"Jul, 2021 to ?"
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",TV,Unknown,Unknown
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy",TV,Unknown,"Jul, 2021 to ?"

In [13]:
unknown = (tabela["Score"] == "Unknown").sum()
display(unknown)
unknown2 = (tabela["Episodes"] == "Unknown").sum()
display(unknown2)
tabela= tabela.drop(tabela[tabela["Score"] == "Unknown"].index)
tabela= tabela.drop(tabela[tabela["Episodes"] == "Unknown"].index)
tabela= tabela.drop(tabela[tabela["Genres"] == "Unknown"].index)
tabela= tabela.drop(tabela[tabela["Aired"] == "Unknown"].index)
display(tabela)

5141

516

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,"Apr 3, 1998 to Apr 24, 1999"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,"Sep 1, 2001"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,"Apr 1, 1998 to Sep 30, 1998"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,"Jul 2, 2002 to Dec 24, 2002"
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,"Sep 30, 2004 to Sep 29, 2005"
...,...,...,...,...,...,...,...
17504,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,4,"Feb 14, 2021"
17505,47402,Heikousen,7.52,"Music, Romance",Music,1,"Feb 5, 2021"
17512,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,1,"Feb 11, 2021"
17513,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,1,"Feb 12, 2021"
17552,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,1,"Mar 14, 2021"

In [14]:
tabela["Aired"] = tabela["Aired"].str.replace(r'\s*to.*$', '', regex=True)
display(tabela)

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,"Apr 3, 1998"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,"Sep 1, 2001"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,"Apr 1, 1998"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,"Jul 2, 2002"
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,"Sep 30, 2004"
...,...,...,...,...,...,...,...
17504,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,4,"Feb 14, 2021"
17505,47402,Heikousen,7.52,"Music, Romance",Music,1,"Feb 5, 2021"
17512,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,1,"Feb 11, 2021"
17513,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,1,"Feb 12, 2021"
17552,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,1,"Mar 14, 2021"

In [15]:
tabela.to_csv("anime_tratado.csv", index=False)