In [7]:
import pandas as pd 

tabela = pd.read_csv("C:/Users/nacli/OneDrive/Área de Trabalho/Faculdade/AEDS3-main/AEDS3-main/ManipulandoBase/anime_tratado.csv")
display(tabela)

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,1998-04-03
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,2001-09-01
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,1998-04-01
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,2002-07-02
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,2004-09-30
...,...,...,...,...,...,...,...
12290,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,4,2021-02-14
12291,47402,Heikousen,7.52,"Music, Romance",Music,1,2021-02-05
12292,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,1,2021-02-11
12293,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,1,2021-02-12
12294,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,1,2021-03-14

In [8]:
display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12295 entries, 0 to 12294
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MAL_ID    12295 non-null  int64
 1   Name      12295 non-null  object
 2   Score     12295 non-null  float64
 3   Genres    12295 non-null  object
 4   Type      12295 non-null  object
 5   Episodes  12295 non-null  int64
 6   Aired     11720 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

None

In [9]:
tabela['Aired'] = tabela['Aired'].str.replace(r'\s*to.*$', '', regex=True)
display(tabela)

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,1998-04-03
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,2001-09-01
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,1998-04-01
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,2002-07-02
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,2004-09-30
...,...,...,...,...,...,...,...
12290,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,4,2021-02-14
12291,47402,Heikousen,7.52,"Music, Romance",Music,1,2021-02-05
12292,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,1,2021-02-11
12293,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,1,2021-02-12
12294,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,1,2021-03-14

In [10]:
def try_parse_date(date_str):
    formats_to_try = ['%b %d, %Y', '%b, %Y']
    
    for fmt in formats_to_try:
        try:
            return pd.to_datetime(date_str, format=fmt)
        except ValueError:
            pass
    
    return None

df = pd.DataFrame(columns=['Aired'])
df['Aired'] = tabela['Aired']
df['Aired_converted'] = df['Aired'].apply(try_parse_date)

df['Aired']= df['Aired_converted']
df.drop(columns=['Aired_converted'], inplace=True)

tabela['Aired'] = df['Aired']


display(tabela)

,MAL_ID,Name,Score,Genres,Type,Episodes,Aired
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,NaT
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,NaT
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,26,NaT
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",TV,26,NaT
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",TV,52,NaT
...,...,...,...,...,...,...,...
12290,47398,Kimetsu Gakuen: Valentine-hen,6.59,Comedy,ONA,4,NaT
12291,47402,Heikousen,7.52,"Music, Romance",Music,1,NaT
12292,47614,Nu Wushen de Canzhuo Spring Festival Special,6.83,"Slice of Life, Comedy",Special,1,NaT
12293,47616,Yakusoku no Neverland 2nd Season: Michishirube,4.81,"Mystery, Psychological, Supernatural, Thriller...",Special,1,NaT
12294,48456,SK∞: Crazy Rock Jam,6.52,"Comedy, Sports",Special,1,NaT

In [ ]:
tabela.to_csv("anime_tratado.csv", index=False)